### ISSUE TITLE
MCLocalization loadFromLanguageURLPairs

### ISSUE THREAD

**Issue by ghousesgb** [Baglan/MCLocalization2#1]
Adding multiple languages

**Comment by Baglan** [comment]
Could you elaborate on that?

**Comment by ghousesgb** [comment]
I was trying to add multiple languages, in objc we had to loadFromLanguageURLPairs.
so, tried with 
MCLocalization.sharedInstance.addProvider(MCLocalization.JSONProvider(language : "English", fileName: **"Espanol.json"))**
        MCLocalization.sharedInstance.addProvider(MCLocalization.JSONProvider(language : "Español", fileName: "Espanol.json"))
        MCLocalization.sharedInstance.addProvider(MCLocalization.JSONProvider(language : "português", fileName: "portugues.json"))

Now the issue is it always selects Espanol values.
any idea why does it?
Found and fixed the issue. 
Sorry for my mistake, :)

**Comment by Baglan** [comment]
Good luck with your project!
